title: Yogesh Balan
markdown: kramdown

url: "yogeshbalan.github.io"
baseurl: "/yogeshbalan"

# for atom feed
author:
  name: Yogesh Balan
  email: me@yogeshbalan.com

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections_dir: all_collections
collections:
  posts:
    output: false

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      #permalink: /posts/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
